environment:
  matrix:
    - nodejs_version: '12'
    - nodejs_version: '8'
    - nodejs_version: '6'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
matrix:
  fast_finish: true
  allow_failures:
    - platform: x86
    - platform: x64
build: off
shallow_clone: true
test_script:
  - node --version
  - npm --version
  - npm test
cache:
  - '%APPDATA%\npm-cache'
